# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  install_ruby:
    runs-on: self-hosted

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libssl-dev libreadline-dev zlib1g-dev \
          libsqlite3-dev libbz2-dev libffi-dev libyaml-dev libgdbm-dev \
          libncurses5-dev libgmp-dev libgmp3-dev

    - name: Install ruby-build
      run: |
        git clone https://github.com/rbenv/ruby-build.git ~/.ruby-build
        echo 'export PATH="$HOME/.ruby-build/bin:$PATH"' >> ~/.bashrc
        source ~/.bashrc

    - name: Install Ruby 3.1.4
      run: |
        export RUBY_CONFIGURE_OPTS="--prefix=$HOME/.ruby"
        ruby-build 3.1.4 $HOME/.ruby
        touch $HOME/.ruby.complete
  build:
    runs-on: ubuntu-22.04  # Set the runner to Ubuntu 22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true  # Automatically runs 'bundle install' and caches installed gems
          cache-version: 0     # Increment this number if you need to re-download cached gems
        
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
        
      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site  # Specifies the directory for the artifact

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04  # Use Ubuntu 22.04 for the deploy job as well
    needs: build  # Ensures the deploy job runs after the build job
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4